In [12]:
import sys



sys.path.append("/home/jovyan/work/sem-covid/")
sys.path = list(set(sys.path))
import os

os.getcwd()
os.chdir('/home/jovyan/work/sem-covid/')
from sklearn import preprocessing
from sem_covid.services.store_registry import StoreRegistry
from pycaret.classification import *
import mlflow
from sem_covid import config


In [1]:
import tensorflow_hub as hub
model_url = "https://tfhub.dev/google/universal-sentence-encoder/4"
model = hub.load(model_url)

In [3]:
emb = model(["Hello world"])

In [10]:
emb.numpy().tolist()

[[-0.02607426419854164,
  -0.08460001647472382,
  -0.026786621659994125,
  0.05678422749042511,
  0.06197047233581543,
  0.038226015865802765,
  0.02011493407189846,
  0.02740876004099846,
  0.08698319643735886,
  0.030791785567998886,
  0.04104117304086685,
  0.025518342852592468,
  0.0009651867439970374,
  0.05892797186970711,
  0.040095411241054535,
  0.046708934009075165,
  -0.033127956092357635,
  0.040704160928726196,
  -0.01199297048151493,
  -0.04761705547571182,
  -0.008296682499349117,
  0.07054674625396729,
  0.004843536298722029,
  0.08098248392343521,
  -0.0570177286863327,
  -0.06435514986515045,
  0.0697147324681282,
  -0.06988384574651718,
  0.026460617780685425,
  -0.02352205291390419,
  0.05523752421140671,
  0.04913639649748802,
  0.056989721953868866,
  -0.061071936041116714,
  0.0360850989818573,
  0.023244615644216537,
  0.05601752549409866,
  -0.010955199599266052,
  0.04213083162903786,
  -0.017695393413305283,
  0.0071243466809391975,
  0.020470306277275085,
  

In [13]:
from gensim.models import KeyedVectors
from sem_covid.services.data_registry import LanguageModel
law2vec = LanguageModel.LAW2VEC.fetch()
law2vec_path = LanguageModel.LAW2VEC.path_to_local_cache()
word2vec = KeyedVectors.load_word2vec_format(law2vec_path, encoding="utf-8")

array([0.45756128, 0.37264929, 0.93881131, 0.05957271, 0.78567591,
       0.1878297 , 0.55212816, 0.19248258, 0.03634315, 0.709277  ,
       0.83987553, 0.3996499 , 0.59314394, 0.31281565, 0.40508458,
       0.52134048, 0.54386873, 0.98496962, 0.37355215, 0.5425929 ,
       0.56345777, 0.18812274, 0.54121338, 0.21317919, 0.64325342,
       0.49107691, 0.91688395, 0.24546619, 0.28981497, 0.14662185,
       0.53759883, 0.75456018, 0.93298609, 0.62832015, 0.74107546,
       0.19652805, 0.35248002, 0.40533377, 0.74908429, 0.27040939,
       0.72828338, 0.38790358, 0.89078037, 0.50883022, 0.90897045,
       0.09713505, 0.82137012, 0.58503822, 0.20404585, 0.48503592,
       0.36996939, 0.79785431, 0.90602852, 0.76222883, 0.81586834,
       0.82445205, 0.99807009, 0.82709976, 0.76621742, 0.46541822,
       0.95712962, 0.46853822, 0.93177205, 0.58054059, 0.56636506,
       0.42591811, 0.45963381, 0.13444624, 0.73669319, 0.3157996 ,
       0.68585751, 0.21624219, 0.34608228, 0.32882417, 0.04894

In [14]:
type(word2vec)

gensim.models.keyedvectors.KeyedVectors

In [19]:
import spacy
nlp = spacy.load("en_core_web_sm")

In [29]:
list(map(str,nlp("hello world my friend")))

['hello', 'world', 'my', 'friend']

In [66]:
sentences = ['Hello, (my big) friend.',
             'this is example of text',
             'code is just a text'
             ]

In [37]:
sentences

['hello my friend', 'this is example of text', 'code is just a text']

In [38]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer


In [105]:
SENTENCES = [
    'Rather than having all of its functionality built into its core.',
    'Python was designed to be highly extensible (with modules).',
    'Rather than having all of its functionality built into its core.',
    'This compact modularity has made it particularly popular as a means of adding programmable interfaces to existing applications.',
    "Van Rossum's vision of a small core language with a large standard library and easily extensible interpreter stemmed from his frustrations with ABC, which espoused the opposite approach."
]

In [113]:
tf_idf_vectors = TfidfVectorizer()
tf_idf_matrix = pd.DataFrame(tf_idf_vectors.fit_transform(SENTENCES).todense().tolist(),
                              columns=tf_idf_vectors.get_feature_names(),
                             )

In [124]:
tf_idf_matrix.iloc[0]

abc              0.000000
adding           0.000000
all              0.286573
and              0.000000
applications     0.000000
approach         0.000000
as               0.000000
be               0.000000
built            0.286573
compact          0.000000
core             0.237882
designed         0.000000
easily           0.000000
espoused         0.000000
existing         0.000000
extensible       0.000000
from             0.000000
frustrations     0.000000
functionality    0.286573
has              0.000000
having           0.286573
highly           0.000000
his              0.000000
interfaces       0.000000
interpreter      0.000000
into             0.286573
it               0.000000
its              0.573147
language         0.000000
large            0.000000
library          0.000000
made             0.000000
means            0.000000
modularity       0.000000
modules          0.000000
of               0.200114
opposite         0.000000
particularly     0.000000
popular     

In [120]:
for index, row in tf_idf_matrix.iterrows():
    print(type(row))

<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>


In [71]:
for iter, row in tf_idf_matrix.iterrows():
    print(row['hello'])

0.5
0.0
0.0


In [88]:
tokens = ['hello', 'my', 'big', 'friend']

In [104]:
tf_idf_matrix.loc['Hello, (my big) friend.'][tokens[0]]


array([1.5, 2.5, 3. ])

In [96]:
np.sum([[1,2],[5,7]],axis=0)/10

array([0.6, 0.9])

In [101]:
3 * np.array([3,5,6])

array([ 9, 15, 18])

In [73]:
np.zeros(10).tolist()

[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

In [79]:
np.mean([[1,2],[2,3],[34,6]],axis=0).tolist()

[12.333333333333334, 3.6666666666666665]

In [3]:
SIMPLE_CLASS_COLUMNS = ['category', 'subcategory', 'type_of_measure', 'target_groups',
                        'actors']

In [2]:
es_store = StoreRegistry.es_index_store()
df = es_store.get_dataframe(config.PWDB_ELASTIC_SEARCH_INDEX_NAME)

100% (1288 of 1288) |####################| Elapsed Time: 0:00:00 Time:  0:00:00


In [4]:
pwdb_dataframe = df
pwdb_dataframe['target_groups'] = pwdb_dataframe['target_groups'].apply(lambda x: "|".join(x))
pwdb_dataframe['actors'] = pwdb_dataframe['actors'].apply(lambda x: "|".join(x))

In [36]:
pwdb_dataframe['actors_label'] = pwdb_dataframe['actors']

In [37]:
pwdb_dataframe[['actors','actors_label']]

actors  \
_id                                                                                                     
adc5c75937bc7f7198f534d08b85bd50c9521bfd3f319a0...  National government|Trade unions|Employers' or...   
2372d71eb9ad6e6a70982e02bbe802db004ed49d91b2264...               National government|Social insurance   
8735e268191e9e5cbd3d2a44ca53d297e31746b5f1e24b9...  National government|Local / regional governmen...   
18bcd22116c46919e03a3345f793c3859855227ac942e69...            National government|Company / Companies   
b94d8aa95fbdeb1bb832b01fbe5d6e9bf9fc36fceb14f7b...                                National government   
...                                                                                               ...   
cb014a456b14c3621dd318a12e611f70c2a9636be9fe181...  National government|Public employment service|...   
d233b17dc2b98f14269c2b22be78d93ec5ccf2a0013b86f...        National government|Social partners jointly   
77d7e3c52aaf78bdfb1a1667641db1293bbff862440c547...                                National government   
be8e21b382b63dd838087d7864e4d49a4807d9cc5d71aaa...                                National government   
c434820f8f8c0b1447ba2f6f62aed177b9597532d7fcd15...                            Social partners jointly   

                                                                                         actors_label  
_id                                                                                                    
adc5c75937bc7f7198f534d08b85bd50c9521bfd3f319a0...  National government|Trade unions|Employers' or...  
2372d71eb9ad6e6a70982e02bbe802db004ed49d91b2264...               National government|Social insurance  
8735e268191e9e5cbd3d2a44ca53d297e31746b5f1e24b9...  National government|Local / regional governmen...  
18bcd22116c46919e03a3345f793c3859855227ac942e69...            National government|Company / Companies  
b94d8aa95fbdeb1bb832b01fbe5d6e9bf9fc36fceb14f7b...                                National government  
...                                                                                               ...  
cb014a456b14c3621dd318a12e611f70c2a9636be9fe181...  National government|Public employment service|...  
d233b17dc2b98f14269c2b22be78d93ec5ccf2a0013b86f...        National government|Social partners jointly  
77d7e3c52aaf78bdfb1a1667641db1293bbff862440c547...                                National government  
be8e21b382b63dd838087d7864e4d49a4807d9cc5d71aaa...                                National government  
c434820f8f8c0b1447ba2f6f62aed177b9597532d7fcd15...                            Social partners jointly  

[1288 rows x 2 columns]

In [38]:
le = preprocessing.LabelEncoder()
le.fit(pwdb_dataframe['actors'])

LabelEncoder()

In [40]:
pwdb_dataframe['actors'] = le.transform(pwdb_dataframe['actors'])

In [43]:
pwdb_dataframe['actors']= le.inverse_transform(pwdb_dataframe['actors'])

In [44]:
pwdb_dataframe['actors']

_id
adc5c75937bc7f7198f534d08b85bd50c9521bfd3f319a090932b5d0bae54de0    National government|Trade unions|Employers' or...
2372d71eb9ad6e6a70982e02bbe802db004ed49d91b2264c0a2e8e41571002cc                 National government|Social insurance
8735e268191e9e5cbd3d2a44ca53d297e31746b5f1e24b941db6225a25848353    National government|Local / regional governmen...
18bcd22116c46919e03a3345f793c3859855227ac942e69dd13cbfcd588e1044              National government|Company / Companies
b94d8aa95fbdeb1bb832b01fbe5d6e9bf9fc36fceb14f7ba370a963f472fe35b                                  National government
                                                                                          ...                        
cb014a456b14c3621dd318a12e611f70c2a9636be9fe181072bd4bf5917a40fa    National government|Public employment service|...
d233b17dc2b98f14269c2b22be78d93ec5ccf2a0013b86f09175c69353c5800b          National government|Social partners jointly
77d7e3c52aaf78bdfb1a1667641db1293bbff862440c547fc3f6

In [20]:
le.classes_

array(['Company / Companies',
       'Company / Companies|Local / regional government',
       'Company / Companies|Local / regional government|Public employment service',
       'Company / Companies|Other social actors (e.g. NGOs)',
       'Company / Companies|Other social actors (e.g. NGOs)|Local / regional government',
       'Company / Companies|Other social actors (e.g. NGOs)|Public support service providers',
       'Company / Companies|Public employment service',
       'Company / Companies|Public support service providers',
       'Company / Companies|Social insurance', 'EU (Council, EC, EP)',
       'EU level social partners', "Employers' organisations",
       "Employers' organisations|Company / Companies",
       "Employers' organisations|Company / Companies|Local / regional government",
       "Employers' organisations|Company / Companies|Other social actors (e.g. NGOs)",
       "Employers' organisations|Company / Companies|Social insurance",
       "Employers' organisation

In [18]:
tmp_classes = pd.DataFrame(le.classes_)

In [30]:
tmp_classes[0].values
tmp_transformed = pd.DataFrame(le.transform(tmp_classes[0].values))

In [33]:
tmp_transformed[1] = tmp_transformed[0].apply(lambda x: tmp_classes[0].values[x])

In [34]:
tmp_transformed

0                                                  1
0      0                                Company / Companies
1      1    Company / Companies|Local / regional government
2      2  Company / Companies|Local / regional governmen...
3      3  Company / Companies|Other social actors (e.g. ...
4      4  Company / Companies|Other social actors (e.g. ...
5      5  Company / Companies|Other social actors (e.g. ...
6      6      Company / Companies|Public employment service
7      7  Company / Companies|Public support service pro...
8      8               Company / Companies|Social insurance
9      9                               EU (Council, EC, EP)
10    10                           EU level social partners
11    11                           Employers' organisations
12    12       Employers' organisations|Company / Companies
13    13  Employers' organisations|Company / Companies|L...
14    14  Employers' organisations|Company / Companies|O...
15    15  Employers' organisations|Company / Companies|S...
16    16  Employers' organisations|Local / regional gove...
17    17  Employers' organisations|Local / regional gove...
18    18                        Local / regional government
19    19  Local / regional government|Public employment ...
20    20                                National government
21    21            National government|Company / Companies
22    22  National government|Company / Companies|EU (Co...
23    23  National government|Company / Companies|Local ...
24    24  National government|Company / Companies|Local ...
25    25  National government|Company / Companies|Local ...
26    26  National government|Company / Companies|Other ...
27    27  National government|Company / Companies|Other ...
28    28  National government|Company / Companies|Other ...
29    29  National government|Company / Companies|Public...
30    30  National government|Company / Companies|Public...
31    31  National government|Company / Companies|Public...
32    32  National government|Company / Companies|Social...
33    33           National government|EU (Council, EC, EP)
34    34  National government|EU level social partners|E...
35    35       National government|Employers' organisations
36    36  National government|Employers' organisations|C...
37    37  National government|Employers' organisations|C...
38    38  National government|Employers' organisations|C...
39    39  National government|Employers' organisations|L...
40    40  National government|Employers' organisations|O...
41    41  National government|Employers' organisations|P...
42    42  National government|Employers' organisations|S...
43    43    National government|Local / regional government
44    44  National government|Local / regional governmen...
45    45  National government|Local / regional governmen...
46    46  National government|Local / regional governmen...
47    47  National government|Local / regional governmen...
48    48  National government|Local / regional governmen...
49    49  National government|Other social actors (e.g. ...
50    50  National government|Other social actors (e.g. ...
51    51  National government|Other social actors (e.g. ...
52    52  National government|Other social actors (e.g. ...
53    53      National government|Public employment service
54    54  National government|Public employment service|...
55    55  National government|Public employment service|...
56    56  National government|Public support service pro...
57    57               National government|Social insurance
58    58  National government|Social insurance|Public su...
59    59        National government|Social partners jointly
60    60  National government|Social partners jointly|Co...
61    61  National government|Social partners jointly|Co...
62    62  National government|Social partners jointly|Co...
63    63  National government|Social partners jointly|Co...
64    64  National government|Social partners jointly|EU...
65    65  National government|Social partners j

In [ ]:
for column in SIMPLE_CLASS_COLUMNS:
    le = preprocessing.LabelEncoder()
    le.fit(pwdb_dataframe[column])
    pwdb_dataframe[column + '_label'] = le.transform(pwdb_dataframe[column])